-- Migration: Add description columns for AI-analyzed content

-- Add description to stories table (for AI-analyzed art style)
ALTER TABLE stories ADD COLUMN IF NOT EXISTS art_style_description TEXT;

-- Add description to characters table (for AI-analyzed character appearance)
ALTER TABLE characters ADD COLUMN IF NOT EXISTS description TEXT;

-- Add description to backgrounds table (for AI-analyzed background/setting)
ALTER TABLE backgrounds ADD COLUMN IF NOT EXISTS description TEXT;

-- These descriptions are automatically generated by Gemini Vision API
-- and can be manually edited by users to improve consistency
