import { GoogleGenAI, Modality } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
const illustrationModel = "gemini-2.5-flash-image";

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { originalImage, editPrompt } = req.body;

  if (!originalImage || !editPrompt) {
    return res.status(400).json({ error: 'Original image and edit prompt are required' });
  }

  try {
    const parts: any[] = [
      {
        inlineData: {
          mimeType: originalImage.mimeType,
          data: originalImage.base64,
        },
      },
      {
        text: `**━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━**
**🎨 IMAGE EDIT REQUEST**
**━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━**

Edit Instruction: "${editPrompt}"

**⚠️ CRITICAL CONSISTENCY REQUIREMENTS:**

**1. PRESERVE EXISTING STYLE (MANDATORY):**
   • Maintain the EXACT art style of the original image
   • Keep the same line work thickness, shading technique, and brush strokes
   • Preserve the color palette and color grading
   • Match the level of detail and artistic quality
   • The edited result MUST look like it's from the same artwork

**2. MINIMAL CHANGES ONLY:**
   • ONLY modify what is explicitly requested in the edit instruction
   • Do NOT change unrelated elements
   • Preserve all other characters, objects, and background elements exactly as they are
   • Maintain the original composition and framing

**3. SEAMLESS INTEGRATION:**
   • Any new or modified elements must blend naturally with the existing style
   • Match lighting, shadows, and atmospheric effects
   • Ensure color harmony with the rest of the image
   • The edit should be undetectable - as if it was always part of the original

**4. QUALITY PRESERVATION:**
   • Maintain the same resolution and image quality
   • Keep the same level of polish and finish
   • Do not introduce artifacts or style inconsistencies

Think of this as carefully retouching a photograph - change ONLY what's requested while keeping everything else identical.`,
      },
    ];

    const response = await ai.models.generateContent({
      model: illustrationModel,
      contents: { parts },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return res.status(200).json({
          image: `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`
        });
      }
    }

    throw new Error("No edited image was generated by the API.");

  } catch (error: any) {
    console.error("Error editing illustration:", error);
    return res.status(500).json({ error: error.message || 'Failed to edit illustration' });
  }
}
